### ISSUE TITLE
Purpose of PropTypes and Interfaces

### ISSUE THREAD

**Issue by tim-soft** [stardust-ui/react#7]
Looking through the Button source, I see that there is a Typescript interface for it's props as well as redundant usage of the PropTypes package.

Is there a reason for using both?

**Comment by Bugaa92** [comment]
PropTypes are useful for run-time checks for expected props and are particularly useful for JS consumers
TypeScript interfaces offer compile time checks and all the goodies of a compiled code (easy access to available API, type safety, auto-complete, etc.)

@levithomason and @mnajdova might have more insight on how to unify these moving forward

**Comment by levithomason** [comment]
### Why have PropTypes?

1. A small subset of the world currently uses TypeScript.  We hope that changes in the coming years.  PropTypes exist primarily for the majority of those users who don't have any other type safety.

2. they can do cool things with values, like this:

    ![image](https://user-images.githubusercontent.com/5067638/43879521-564ee136-9b59-11e8-8efd-ac0b71e67154.png)

    Value checks cannot be done in TypeScript.  You also cannot get help at this level ^ with TS.  Even when using typescript, there are cases where this kind of thing comes up at run time.

3. Currently our docs and component info files are generated from the PropType info.  That AST crawling logic needs to be moved to the crawling the TS interfaces before we can remove them.  Otherwise, we can't generate docs or run our automated conformance tests.

4. I was going to say propTypes are stripped in production, however, it looks like we lost that feature at some point after forking off of Semantic UI React 😕 We should fix that...

### Why remove them?

1. It is a pain to maintain both.  We could generate simplified typings from our interfaces someday.  Perhaps we will.  Until then, we have both.

***

Would love to hear other's thoughts and input on this as well.

**Comment by levithomason** [comment]
Closing for housekeeping.  Let us know if there are still questions around this and we'll answer them.
