### ISSUE TITLE
[RFC] MenuItem Children API

### ISSUE THREAD

**Issue by miroslavstastny** [stardust-ui/react#79]
When implementing menu accessibility (#61), `MenuItem` (which by default renders as `li > a`) was modified and onClick handler as well as several styling were moved from `li` to `a`.

That works correctly for ShorthandApi, but unfortunately it breaks ChildrenApi. It was agreed previously that `<Menu.Item>children</MenuItem>` renders as `<li>children</li>`.
That worked previously as all the styles and onClick were on the li, but it is broken now.

I was thinking about splitting `ListItem` to `ListItem` (which renders as `li`) and `ListItemLink` (which renders as `a`). I played with the code to test this approach and it seems to work. The only problem I see is that a developer must pass the same props to several components:

```jsx
<Menu>
  <Menu.Item>
    <Menu.Item.Link>
    </Menu.Item.Link>
  </Menu.Item>
</Menu>
```

Now if you want to make the menu to be **vertical**, you must add `vertical` to all `Menu`, `Menu.Item` and `Menu.Item.Link`. For an active item, you must add `active` to both `Menu.Item` and `Menu.Item.Link`.

What is our plan for supporting Children API?

**Comment by levithomason** [comment]
@brianespinosa / @layershifter / @fracmak - If possible, could you review the above convo regarding children vs shorthand and offer any input?  I respect all of your engineering and experience much on this.

**Comment by brianespinosa** [comment]
I'll take a dig through my current application and see if I can find the places where we have opted for using the Child API versus Shorthand API. I think those Child API cases were because we needed to do some special/tricky work extending the internal markup of a component to meet some of our UI needs. In one case I believe it ended up being more work trying to do things this way and override some existing styles than to make a new custom component instead.

My initial inclination is that not supporting Child API at first is probably fine. And from a user experience perspective, I think a LOT of the questions we would get daily were from people not getting the out of the box functionality where it *Just Works™*.

I think if we DO end up supporting Child API we maybe explicitly cover that support in the docs with a warning that says using the Child API is for advanced use and some functionality will not magically work. Basically the Child API is you are mostly on your own and you have to know where prop drilling is happening, etc.

**Comment by fracmak** [comment]
I'll give it some thought, but I think we need to make certain we're consistent across all components. It's tough when you have to keep a mental list of what components are given shorthand and which use children. I personally really like the children api over the shorthand, but I do understand why it doesn't work for certain interactions (Dropdown is a good example). At which point it might make sense to do away with all children apis unless it's something like a popup or a modal where you are filling the component with your own content.

**Comment by miroslavstastny** [comment]
`Menu` currently supports shorthand API only
