### ISSUE TITLE
Red file names in VS Code? 

### ISSUE THREAD

**Issue by bcalvery** [stardust-ui/react#95]
Whenever I open a file in VS Code I'm getting warnings/red text, which is really difficult to ignore. It seems to be caused by the first line `import React from 'react'`, which is showing the error `[ts] Module '"d:/Dev/stardust-react/node_modules/@types/react/index"' has no default export.`.
![image](https://user-images.githubusercontent.com/15043460/44165844-aa66fe00-a07e-11e8-92df-076385e824f4.png)
Changing the first line of the file to `import * as React from 'react'` does fix it. Is this an acceptable change to make in the files I'm working in?

**Comment by davezuko** [comment]
Should be fixed by https://github.com/stardust-ui/react/pull/96.

**Comment by levithomason** [comment]
Indeed.  The longer term fix here is to either (in order of preference):

1. Write examples in fully typed TypeScript but strip the type syntax in public facing examples.
1. Decide to show examples in TypeScript, which I don't think is good for the larger community, yet.
2. Write examples in JS, which is not great since we lose all type safety there.

**Comment by levithomason** [comment]
Closing as #96 takes care of the original post.
